### ISSUE TITLE
About XbimMemoryModel

### ISSUE THREAD

**Issue by azura-vergo** [xBimTeam/XbimEssentials#10]
I want to ask a question
Form codeplex, there is a class name XbimMemoryModel,but i can not find it in the source code package of Xbim.XbimExtensions

//   ----   code from codeplex    --------------
Xbim.XbimExtensions.IModel model = null;     

//get a stream to access the ifc data
Xbim.IO.IfcInputStream input = new Xbim.IO.IfcInputStream(new FileStream(ifcFileName, FileMode.Open, FileAccess.Read)); 

//create an empty model
model = new Xbim.XbimExtensions.XbimMemoryModel(); 

//load entities into the model
errors = input.Load(model);
//   ----   end   --------------

and this is the link 
http://xbim.codeplex.com/wikipage?title=Walkthrough%20Sample%201%3A%20Export%20data%20from%20an%20IFC%20File%20to%20an%20Excel%20Spreadsheet

is this XbimMemoryModel built model fast than XbimModel?
where i can get this XbimMemoryModel

**Comment by CBenghi** [comment]
XbimMemoryModel was discontinued at some point in the past for a number of reasons.
We have since refactored the whole solution and there are plans to bring a new memory model in the solution shortly, but it's only available in Essentials at the moment.
You can have a look at that in essential (branch is origin/feature/Schema_transition_framework)
Best,
Claudio

**Comment by azura-vergo** [comment]
thank you so much
