### ISSUE TITLE
productId of object in WexBIM and its corresponding element Guid

### ISSUE THREAD

**Issue by jdimyadi** [xBimTeam/XbimEssentials#110]
Hi

Any suggestion as to how one might be able to get the productId of an object in WexBIM model given the Guid of the same element in the IFC file? An example use case, selecting an IfcDoor in the IFC file would then highlight the object in WexBIM.

**Comment by martin1cerny** [comment]
Because of WebGL constrains it is only possible to use integer as a key to work with entities. ID you get from the wexBIM file is what you find as EntityLabel using xBIM. And it is also the number at the beginning of the line in IFC Step 21 file. You can think of it as a locally unique ID. You can search by both keys in xBIM which gives you the link.

**Comment by jdimyadi** [comment]
Thanks, Martin
