### ISSUE TITLE
Error open an ifcxml file

### ISSUE THREAD

**Issue by Thomas-E-A** [xBimTeam/XbimEssentials#138]
Hi,
when I open the ifcxml file I get this exception:
{"UnitsInContextis not an IPersistEntity type"}
call stack:
Xbim.IO.Xml.XbimXmlReader4.ReadEntity(XmlReader input) 
in ...\Xbim.IO\Xml\XbimXmlReader4.cs:Zeile 185.
Xbim.IO.Xml.XbimXmlReader4.SetPropertyFromElement(ExpressMetaProperty property, IPersistEntity entity, XmlReader input, Int32[] pos, ExpressType valueType) 
in ...\Xbim.IO\Xml\XbimXmlReader4.cs:Zeile 377.
Xbim.IO.Xml.XbimXmlReader4.ReadEntity(XmlReader input) 
in ...\Xbim.IO\Xml\XbimXmlReader4.cs:Zeile 218.
Xbim.IO.Xml.XbimXmlReader4.Read(Stream xmlStream, Boolean onlyHeader) 
in ...\Xbim.IO\Xml\XbimXmlReader4.cs:Zeile 118.
Xbim.IO.Memory.MemoryModel.LoadXml(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate) 
in ...\Xbim.IO\Memory\MemoryModel.cs:Zeile 375.
Xbim.IO.Memory.MemoryModel.LoadXml(String path, ReportProgressDelegate progDelegate) 
in ...\Xbim.IO\Memory\MemoryModel.cs:Zeile 355.

I'm using NuGet packages
Xbim.Essentials v4.0.29
Xbim.Geometry v4.0.11

The file seems to be valid it is attached

Thanks
[CC20-Musterdatei.zip](https://github.com/xBimTeam/XbimEssentials/files/1840832/CC20-Musterdatei.zip)

**Comment by martin1cerny** [comment]
Hi Thomas,

I'll have a look at this.

Martin

**Comment by martin1cerny** [comment]
Right, I found it and fixed. Will push to develop soon. The problem is that there are not very many IFC4 XML files around. And all files we had for testing were defining the type of the node explicitly as a XML attribute. But that is obviously not necessary in some cases where the type of IFC element is a non-abstract entity with no descendants and implicit typing is possible.
