### ISSUE TITLE
How to write code unified for IFC2x3 and IFC4 to get properties?

### ISSUE THREAD

**Issue by I-Sokolov** [xBimTeam/XbimEssentials#170]
1. I want to have code that works both for IFC2x3 and IFC4.
GetPropertySingleNominalValue is a member of IfcObject
How to rework a fragment like below?

2. How to access a property of Ifc4.Kernel.IfcProject : public IfcObjectDefinition?
IfcRelDefinesByProperties was changed in IFC4 RelatedObjects from IfcObject to IfcObjectDefinition
but GetProperties* are still members of IfcObject

```
            if (Model.IfcSchemaVersion == Common.Step21.IfcSchemaVersion.Ifc2X3)
                {
                var ifcBuilding4 = Model.FederatedInstances.OfType<Ifc2x3.ProductExtension.IfcBuilding> ().FirstOrDefault ();
                ifcBuilding4.GetPropertySingleNominalValue ("Other", "COBieCreatedBy");
                }
            else
                {
                var ifcBuilding4 = Model.FederatedInstances.OfType<Ifc4.ProductExtension.IfcBuilding> ().FirstOrDefault ();
                ifcBuilding4.GetPropertySingleNominalValue ("Other", "COBieCreatedBy");
                }

```

**Comment by Vizzr** [comment]
1. Use the interfaces.

So in your case it would be:
Model.FederatedInstances.OfType<IIfcBuilding>().FirstOrDefault();

**Comment by I-Sokolov** [comment]
@Vizzr, what interface has methods to access property?

**Comment by martin1cerny** [comment]
Please, read the [docs](http://docs.xbim.net/examples/basic-model-operations.html), especially the 'Retrieve' part. It describes and shows how IFC4 interfaces can be used for schema agnostic data retrieval.

**Comment by I-Sokolov** [comment]
This part of doc suggests enumerate all RelByTypes.
It will make hard to port XbimExchange for IFC4 until we have GetProperty* in some common interface for 2x3 and 4.
Or did I miss something?

**Comment by martin1cerny** [comment]
Some parts of XbimExchange use static extensions which were created before we implemented IFC4 and created IFC4 interfaces for IFC2x3. So, this is largely legacy code. If you go to the source of these extensions you will find that it is easy to port to IFC4 interfaces. We didn't do this intentionally because these extensions often hide the lower level data structures and using them in some scenarios leads to poor performance. It is better to have complete implementation in one place to see and control the processing flow with potential cache.
