### ISSUE TITLE
IfcStore equality failure

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimEssentials#179]
#### Expected behavior:

It should be possible to add and retrieve an IfcStore from a dictionary.

#### Actual behavior or exception details:

No exception is thrown, but the key is not found in the dictionary when opening an xbim file.
A test case has been added to current develop branch.

#### Minimal code (or steps) to reproduce the issue:

Test methods have been added to the develop branch with commits 8a5d415cdee356c044c040a09bf05226cb8f5be1 and 3270a91d4157177edded92aa90d5e2d597789837

If the behaviour is by design we should write a clear set of instructions on how to workaround.

**Comment by CBenghi** [comment]
@martin1cerny, am I missing something important on the management of IfcStores here?

**Comment by martin1cerny** [comment]
IfcStore is essentially a wrapper for either memory model or Esent model. So, if you use `IPersistEntity.Model` you will get underlying model instead of `IfcSore`. So, equality should be comparing both internal model and the store. There was a bug which is fixed now.

BTW: To make all this a lot cleaner I think it would be best to make `IfcStore` pure static helper which would return just `IModel` when opening the file. It would hook in delegates automating owner history management and could be used to save the model in particular form.

**Comment by CBenghi** [comment]
Making IfcStore static with the conversion functions seems a clearer solution to me.
It's going to need to wait for a while if we want to mark the class deprecated.
I would do it after we have sorted a stable release that we maintain for a while.
E.g. like what I've done with the xbim3 branch for a bit with essential fixes.
