### ISSUE TITLE
Point Cloud to IFC

### ISSUE THREAD

**Issue by laraomar** [xBimTeam/XbimEssentials#184]
Kindly, I need to construct IFC Standard from Point Clouds Data, How I could do this using XBim and What are the procedures ???

**Comment by martin1cerny** [comment]
Well, you should first look at our [examples](http://docs.xbim.net/examples/examples-list.html), mainly the [wall example](http://docs.xbim.net/examples/proper-wall-in-3d.html) which shows how to create a 3D model of a product.  

IFC4 has a support for point clouds so you store it as [IfcShapeRepresentationon](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcshaperepresentation.htm) with `IfcShapeRepresentationon.Identifier = 'Body'` and `IfcShapeRepresentationon.Type = 'PointCloud'` where all `Items` will be of type [IfcCartesianPointList3D](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifccartesianpointlist3d.htm).

If you have a mesh built from the point cloud you can also store it as  [IfcShapeRepresentationon](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcshaperepresentation.htm) with `IfcShapeRepresentationon.Identifier = 'Body'` and `IfcShapeRepresentationon.Type = 'SurfaceModel'` where all `Items` will be of type [IfcTeselatedItem](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifctessellateditem.htm), [IfcShellBasedSurfaceModel](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcshellbasedsurfacemodel.htm) or [IfcFaceBasedSurfaceModel](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcfacebasedsurfacemodel.htm) depending on what you have as a source.

xBIM implements 100% of the IFC standard so you can use it to create anything defined in the [documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html). You will probably need to study it carefully. IFC models are usually built around products so you might want to classify the pointcloud first to create added value model. Or, you can just assign all geometry to `IfcSite` or `IfcBuilding` and it will be correct as well. If you target any specific SW to consume your IFC you are better to continuously check what it can actually process because many SW only support subsets of IFC.

**Comment by laraomar** [comment]
Dear Martin;
I already have a classified point cloud file ( PLY Format) with the XYZ points of each point. I need to construct IFC Standard format for each classified item. Kindly, I need the source code written in C#, which provides the ability to transfer Point clouds to IFC2x3 TC1 standard.

**Comment by martin1cerny** [comment]
IFC2x3 TC1 is badly suited for point cloud data. But it is doable. 

I'm sorry but the level of support you request exceeds the scope of GitHub issue and would only be possible as a paid-for service.

**Comment by laraomar** [comment]
A Paid for service is accepted, I can clarify more my scope of work to know accurately how much it will cost.

**Comment by martin1cerny** [comment]
You can try to describe it here on GitHub or [this](https://www.linkedin.com/in/martin-cerny/) is my LinkedIn profile where you can send me a private message. I can try to ask the fellow developers if anybody is interested in this kind of development/consultancy.

**Comment by laraomar** [comment]
Dear Martin
As previewed, this is a screen shot from a point cloud file ( PLY-Format). This point cloud represent an indoor living room composed of 5 components. The requirements are:
1) Classify this point clouds into five components
2) Construct an IFC2x3 TC1 standard per each point cloud component 
![point clouds](https://user-images.githubusercontent.com/40602171/42035550-806088e4-7ae3-11e8-946e-506c240643eb.jpg)

**Comment by martin1cerny** [comment]
Can you add additional step and produce some kind of surface for every component? Or is it a requirement to store the actual pointcloud?

**Comment by laraomar** [comment]
No it is a requirement to store the actual pointcloud

**Comment by martin1cerny** [comment]
IFC2x3 has very poor support for large sets of points so your files will be large. But you can use `IfcShapeRepresentationon.Identifier = 'Body'` and `IfcShapeRepresentationon.Type = 'GeometricSet'` where all Items will be of type `IfcPoint`. I'm just not sure if the receiving application will make any sense out of this. Most of the applications I know will probably show an empty scene because point is a 0D geometry unless you put something like a small sphere to the point placement.

**Comment by laraomar** [comment]
Dear martin 
We can use any other format rather than Ifc 2x3

**Comment by CBenghi** [comment]
@laraomar,

previously in the thread you say that you need `the ability to transfer Point clouds to IFC2x3 TC1 standard.`, so it's confusing to see you ask for an alternative storage than that.
Can you please elaborate on your actual needs?

Thanks

**Comment by martin1cerny** [comment]
@laraomar, is there way way I can contact you with private message?

**Comment by laraomar** [comment]
Yes sure, here is my mail
Ahmedgoudagh@gmail.com
