### ISSUE TITLE
Assemblies not signed in V 5.0

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimEssentials#225]
Hi there
many thanks for deploying a new master, but there is no signing of any assembly.
Without signing we have problems to integrate those files in our solution.
Günter

**Comment by martin1cerny** [comment]
Hi @guenter1holzeder, this is an intentional change we made. We are investing our effort to move closer to multiplatform deployment of xBIM and signing is more of a legacy as you can read in [this .NET article](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md). Strong naming is in no way a security measure but only ensures identity. It should not be confused with [code signing](https://en.wikipedia.org/wiki/Code_signing) which we never did as it is a responsibility of the application developer, not the library. 

If you need a strong named assembly feel free to make a clone and sign it for your purposes. Looking at the deployments we think it causes more problems than it solves.

**Comment by martin1cerny** [comment]
Further reasoning about non-signing can be found [here](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/)

**Comment by guenter1holzeder** [comment]
Hi @martin1cerny, I agree with your arguments, but look at the update of your last link. It seems to exist a kind of [dissension](https://www.pedrolamas.com/2018/09/11/start-strong-naming-your-assemblies/) for the right way ;-)

**Comment by andyward** [comment]
What's the general view on this? Do we have a "seconder"?  😄 

The wider .NET consensus seems to be that SNKs are not worth doing these days, but I guess we could put them back in.

What's the rationale?  Are you using the GAC? Or are you looking to prove authenticity of the DLLs? Or is it just that upstream components are forcing strong-naming down-stream?

**Comment by guenter1holzeder** [comment]
We are working with signed COM-Interop. So there is a chain of dependencies which we cannot break currently.

**Comment by andyward** [comment]
OK. I guess we'd better put this all back in again 😄

**Comment by guenter1holzeder** [comment]
Great news 👍

**Comment by andyward** [comment]
All done. You should be able to confirm in Myget

- [x] Essentials (develop & PR'd to master)
- [x] Geometry (develop only)
- [x] WindowsUI / Xplorer (develop only)
- [x] Exchange (develop only)
- [x] COBieExpress (develop & PR'd to master)
