### ISSUE TITLE
Alternative for Xbim.IO.Memory.MemoryModel.GetFileHeader

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimEssentials#229]
On the way to migrate V5...

What is the alternative for the missing method Xbim.IO.Memory.MemoryModel.GetFileHeader()?

I tried EsentModel.GetStepFileHeader() which results in an exception!!

**Comment by andyward** [comment]
The `IModel.Header` property should do the trick. I'll add this to the change log. Suspect it went in v3-v4 rather than 5.

**Comment by guenter1holzeder** [comment]
Yes, I can get the header by that property. But therefor the parser reads the WHOLE schema with all entities which results in bad performance needing ONLY header Information from large files. 

Maybe there is a work arround I didn't find yet!?

**Comment by andyward** [comment]
@martin1cerny may know why this change was made, but it looks like you could read the header yourself like this. Maybe we need to expose this as a dedicated service

https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Common/Model/StepModel.cs#L86

**Comment by guenter1holzeder** [comment]
Ok, the work arround via dummy construction of StepModel will work for us but is not as pretty as the old method GetFileHeader ;-)

**Comment by andyward** [comment]
@martin1cerny Was there a reason we got rid of this? Should we add back a less obtuse means of reading the file header without a full parse?

**Comment by martin1cerny** [comment]
The reason was that we were using parser to read the header and the only way to stop the parser was to call `yycancel()` which was throwing en exception internally. As this is not the right practise we changed it to use a pure scanner where cancellation is straightforward. We are only using this to get the file schema to initialize the right schema implementation. So, there are functions how which get the schema in this way. Reading the complete header was lost in this process but we can put it back.

**Comment by guenter1holzeder** [comment]
Please put it back, because the work arround mentioned above does not the same job as the method. We don't get the full header data and have therefore a loss of information.

**Comment by martin1cerny** [comment]
You can use ` var header = StepModel.LoadStep21Header(s);` now.

**Comment by guenter1holzeder** [comment]
Great job, thanks a lot
