### ISSUE TITLE
Xbim Parser Exception: Too many errors. XbimXplorer opens normaly

### ISSUE THREAD

**Issue by brayner1** [xBimTeam/XbimEssentials#232]
I'm using Xbim Essentials v.4.0.29, and i'm getting the following exception:
Xbim.Common.Exceptions.XbimParserException: 'Too many errors in file, parser execution terminated

I have searched the problem in the internet, and found the [Issue #231 
127](https://github.com/xBimTeam/XbimEssentials/issues/127), and understood that it is an error in which these files are not IFC4 schema compliant. 
But the reason i'm opening this issue is that the latest XbimXplorer downloaded from the Xbim website is opening the same file normaly. It throws 100 of the following error:
==== 16:50	ERROR	Xbim.IO.Step21.XbimP21Parser
Entity #2221325 IFCRELCONNECTSPORTTOELEMENT, error at parameter 6-RelatedElement value = #1253092=IFCBUILDINGELEMENTPROXY

But in the end, the file is loaded and the model appears in the viewer.

The error is exactly on the following line of code:

```csharp
using (var model = IfcStore.Open(Path.ChangeExtension(inPath, "ifc")))
{
    ...
}
```
Is there any way to just ignore these errors, like the XbimXplorer is aparently doing?

Unfortunely, i can't share the file publicly, because it is protected by and NDA.

Thank you,
Rodrigo

**Comment by brayner1** [comment]
After some more investigation, i've found that the class XbimP21Parser has a static variable MaxErrorCount that you can edit before calling the function _IfcStore.Open_  like this:

```csharp
XbimP21Parser.MaxErrorCount = n;
using (var model = IfcStore.Open(Path.ChangeExtension(inPath, "ifc")))
{
    ...
}
```

Hope this can help someone who might come across this problem.

**Comment by martin1cerny** [comment]
You should have a look at the latest xBIM version. We have changed the way we count errors. We were counting every single error in the file before which was not scalable because most of these errors are systematic errors caused by certain patterns in some exporters producing invalid IFC data. In the latest version we count types of errors instead. So, if there is an invalid type assignment for example (assigning entity of certain type to attribute of incompatible type) we only count it once even if it appears thousand times in the file.
