### ISSUE TITLE
[ISSUE][NUGET] Empty nuget package

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#233]
All my nuget package from your project build in 5.0 seems to be empty when I download them. 
To be sure it wasn't an issue from my side I tried with other package like Newtonsoft JSON and it works.

**Comment by martin1cerny** [comment]
I just tried a minimal example and it works fine. Can you post a non-working example?

**Comment by liszto** [comment]
It is in my unity project. 
There is a nuget package manager. 
When I use it, all is correctly download (even all the dependancies) but the lib folder from your packages remains empty where as all dependancies are filled.

I try to figure out why this happens only with your 2 xBim repositories.

**Comment by martin1cerny** [comment]
Paths have changed in the package because we upgraded to .NET Standard 2.0 and .NET 4.7
Also, Xbim.Essentials is only a metapackage now, pointing to a package-per-dll packages.

**Comment by liszto** [comment]
Yeah I see that but all the package per dll remains empty. 
I need to figure out if it's a bug with the nuget package manager in Unity.

**Comment by martin1cerny** [comment]
I would think so. I just tried to create a vanilla project referencing our latest NuGet packages and everything works fine. You might also try to clear any cache your environment might be using.

**Comment by andyward** [comment]
I think I hit this yesterday when upgrading XbimUtilities... I believe it's a bug in Nuget. What seems to be happening is it's uninstalling the prior XBIMEssentials package but failing to fully install the new version (which is a meta package). I think the cause is because we upgrade the .net dependency from net45 to net 47 on the Essentials dependencies.

The solution seems to be to upgrade your project files to net47 **before** you upgrade the nuget packages.

**Comment by andyward** [comment]
Hopefully that works for you. 

I've added a note to the Changelog: 48842eaa1509a7b20ff305b1fcec60deb8231d58
