### ISSUE TITLE
[QUESTION] Selecting all properties in QuantityArea

### ISSUE THREAD

**Issue by GravTrainee** [xBimTeam/XbimEssentials#237]
Hi,

I have started to study IFC and XBIM for my company only recently but I have found it to be extremely interesting. I checked all of your examples but I could not find a solution to my problem. 

I have gotten a hold of some IFC files and I am trying to write a program that could list all of the areas and volumes of spaces and found one your examples. But I do not understand the GetArea functions ending, where you have given the advice to search for multiple properties by using the name, rather than the FirstOrDefault. 

What command should I be using here?

Yours
GravTrainee

**Comment by martin1cerny** [comment]
That depends on the logic you want to apply. There can be any number of quantity areas assigned to any product. 


From: GravTrainee
Sent: 07 January 2019 15:14
To: xBimTeam/XbimEssentials
Cc: Subscribed
Subject: [xBimTeam/XbimEssentials] [QUESTION] Selecting all properties inQuantityArea (#237)

Hi,
I have started to study IFC and XBIM for my company only recently but I have found it to be extremely interesting. I checked all of your examples but I could not find a solution to my problem.
I have gotten a hold of some IFC files and I am trying to write a program that could list all of the areas and volumes of spaces and found one your examples. But I do not understand the GetArea functions ending, where you have given the advice to search for multiple properties by using the name, rather than the FirstOrDefault.
What command should I be using here?
Yours
GravTrainee

**Comment by GravTrainee** [comment]
private static IIfcValue GetArea(IIfcProduct product)
        {
            //try to get the value from quantities first
            var area =
                //get all relations which can define property and quantity sets
                product.IsDefinedBy

                //Search across all property and quantity sets. 
                //You might also want to search in a specific quantity set by name
                .SelectMany(r => r.RelatingPropertyDefinition.PropertySetDefinitions)

                //Only consider quantity sets in this case.
                .OfType<IIfcElementQuantity>()

                //Get all quantities from all quantity sets
                .SelectMany(qset => qset.Quantities)

                //We are only interested in areas 
                .OfType<IIfcQuantityArea>()

                //We will take the first one. There might obviously be more than one area properties
                //so you might want to check the name. But we will keep it simple for this example.
                .FirstOrDefault()
                .AreaValue;

            if (area != null)
                return area;

            //try to get the value from properties
            return null;

In this line of code, what can I replace the FirstOrDefault with, if I wanted to examine the areas and volumes of more complex spaces? I've tried Name and FullName, but they don't seem to match together with that.

**Comment by GravTrainee** [comment]
Let me change my question. What would be the easiest way for me to extract the areas and volumes of different spaces? After googling for a while, I have come to the conclusion, that Xbim Geometry is the only way,  and calculate through the coordinates. Which brings me to my next question: How do I found out the coordinates for a space? I have an example how to get the coordinates of walls, but it doesn't work for spaces. Any suggestions or tutorials to point me to?

Sincerely yours
GravTrainee

**Comment by andyward** [comment]
Why don't you post some code up in https://github.com/xBimTeam/XbimGeometry/ so we can take a look?

You could also look at https://github.com/xBimTeam/XbimGeometry/issues/139

**Comment by GravTrainee** [comment]
Thank you for your quick answer Andy. 
I got a lot of progress done, thanks to Truning's code. The only problem I have is with the AreaOfMesh function and trying to figure out how to tell my program when to set the boolean right, but I can ask that from the code's original creator, thank you very much for your help.
