### ISSUE TITLE
Microsoft.Extensions.Logging Dependencies

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimEssentials#241]
Hi everyone,

First, congrats on the newest release! May the code gods give it stability :D

I've just updated the NuGet packages to the newest version and noticed that the new dependency to MS.Logging triggered a whole bunch of new NuGet dependencies itself. I understand the need to decouple from log4net and abstract the logger so the clients can choose the concrete logger implementation but this MS's "abstraction" is a bit overkill don't you think? Here is my changeset right now:

![image](https://user-images.githubusercontent.com/5221157/51242061-5dfe5200-197f-11e9-89ed-b2914c7d172d.png)

That's 14 packages (.dlls) just for logging abstraction! That's kind of bloated IMO.

Was curious on your guys' take on this. Why did you decide to move to MS.Logging, why not just write a simple logging abstraction on your own?

Cheers

**Comment by andyward** [comment]
Have looked at NodeJs recently? ;-) 

![image](https://user-images.githubusercontent.com/923699/51268492-29f35300-19b8-11e9-959b-3bda14067cd0.png)

But yes, we did have this discussion a bit back: https://github.com/xBimTeam/XbimEssentials/issues/235#issuecomment-448565762

We ended up adopting Microsoft.Extensions.Logging interfaces as it's pretty much defacto in any new netstandard project and it means libraries can be agnostic of the eventual logging solution employed in the end application. i.e. You can use NLog, Serilog, Loggr, or good old log4net if you want. But we also wanted a default ILoggerFactory implementation without forcing the new DI system on everyone which is why Microsoft.Extensions.Logging is included.

If you're using C# and get the chance I'd recommend upgrading to the new 'SDK' csproj format as it'll make your dependencies a lot clearer - so your References are not crowded out with these extra packages.

BTW, why are you checking in your packages folder?

**Comment by urosjovanovic** [comment]
Thanks for the explanation. I will indeed check whether we can upgrade to the new csproj format, at least where possible.

We prefer to check-in the packages folder, since we don't have a lot of external NuGet references (well, now we have :D) and don't wan't to rely on Internet availability in order to build the solution from scratch.

**Comment by andyward** [comment]
Fair enough - as long as it's a conscious decision; Can we close?
