### ISSUE TITLE
How to retrieve the i1234 number in IfcXML files?

### ISSUE THREAD

**Issue by klacol** [xBimTeam/XbimEssentials#246]
When creating an IFC file with the XBim toolkit, one can choose to create an IfcXML edition of the file. The IfcXML has no line numbers like the STEP file. In the IfcXML file are the `Id` attributes used for referencing the elements/objects.

When I open an IfcXML  with XBim essentials, I do not find the value of the `Id` attribute of an element. Is it possible to get it?

Something like this:

```csharp
IIfcPropertyTemplate propertyTemplate = GetMyPropertyTemplate(somehow)
string myId = propertyTemplate.Id
```

**Comment by martin1cerny** [comment]
xBIM doesn't persist this mapping by default because in extreme case XML elements might have no IDs at all so we consider them to be informative and only usable for XML parsing. But if you want to get this information you can use lower level functions like this:

https://github.com/martin1cerny/ProductData/blob/master/Tools/SchemaValidator/Validator.cs#L449

**Comment by klacol** [comment]
Thank you!! Workes like a charm.
