### ISSUE TITLE
Displaying a 3D annotation in BIM viewers

### ISSUE THREAD

**Issue by carlosbritoccg** [xBimTeam/XbimEssentials#251]
Hello,

We're developing an MR application (with Microsoft's HoloLens) that allows for adding 3D annotations to an architectural model. These annotations are attached to particular elements in the building (such as walls or doors) and as such, have a specific position within them, as well as informative text. We represent the annotation itself with an instance of the IfcAnnotation class with an IfcShapeRepresentation (IfcBoundingBox) for geometry.
This annotation is correctly represented when opening the IFC file in xBimXplorer, however other applications, such as Autodesk Revit or BIM vision ignore it (actually BIM vision is aware of the annotation, but considers that it doesn't have a geometric representation or placement).
We would like to know if there's something we might be missing in our code, or if something we're doing is not standard.

#### Steps (or code) to reproduce the issue:

We include the relevant code of our application:

```csharp
 static void AddAnnotation(IfcStore model, string objectGuid, string name, string description, double x, double y, double z)
        {
            double boxSize = 0.2;

            var element = model.Instances.FirstOrDefault<IfcElement>(d => d.GlobalId == objectGuid);

            using (var txn = model.BeginTransaction("Add Annotation " + name))
            {
                var pPlacement = model.Instances.New<IfcLocalPlacement>(pPlace =>
                {
                    pPlace.PlacementRelTo = element.ObjectPlacement;

                    var placement = model.Instances.New<IfcAxis2Placement3D>();

                    pPlace.RelativePlacement = placement;

                    placement.Location = model.Instances.New<IfcCartesianPoint>(p => p.SetXYZ(x, y, z));
                });

                // model as box
                var body = model.Instances.New<IfcBoundingBox>();
                body.Corner = model.Instances.New<IfcCartesianPoint>(p => p.SetXYZ(-0.5 * boxSize, -0.5 * boxSize, -0.5 * boxSize));

                var dim = new IfcPositiveLengthMeasure(boxSize);

                body.XDim = dim;
                body.YDim = dim;
                body.ZDim = dim;

                // Create a Definition shape to hold the geometry
                var shape = model.Instances.New<IfcShapeRepresentation>();
                var modelContext = model.Instances.OfType<IfcGeometricRepresentationContext>().FirstOrDefault();
                shape.ContextOfItems = modelContext;
                
                shape.RepresentationType = "BoundingBox";
                shape.RepresentationIdentifier = "Body";
                shape.Items.Add(body);
                
                // Create a Product Definition and add the model geometry to the wall
                var rep = model.Instances.New<IfcProductDefinitionShape>();
                
                rep.Representations.Add(shape);

                var pAnnotation = model.Instances.New<IfcAnnotation>(r =>
                {
                    r.GlobalId = IfcGloballyUniqueId.FromGuid(Guid.NewGuid());

                    r.Name = name;
                    r.Description = description;

                    r.ObjectType = new IfcLabel("LOL");

                    r.ObjectPlacement = pPlacement;
                    r.Representation = rep;
                });

                element.ContainedInStructure.FirstOrDefault().RelatedElements.Add(pAnnotation);

                Console.WriteLine("Added annotation: " + name + "/" + description + " to object " + objectGuid + " at (" + x + ", " + y + ", " + z + ")");

                // Commit changes
                txn.Commit();
            }
        }
    }
```

#### Minimal file to reproduce the issue:

This is an annotated file, as output of the above program.
[annotated.zip](https://github.com/xBimTeam/XbimEssentials/files/2905891/annotated.zip)

#### Expected behavior:
We would like to visualize the annotation with other software.

#### Actual behavior or exception details:

Autodesk Revit fully ignores the annotation, while BIM vision displays the annotation without geometrical representation or placement.

**Comment by martin1cerny** [comment]
Hi @carlosbritoccg, this sounds like an exciting application and I'm glad you have chosen xBIM for this. Your code seems to be all right at first look. The only place you might want to check is the part where you are selecting an existing model context:

```cs
 var modelContext = model.Instances.OfType<IfcGeometricRepresentationContext>().FirstOrDefault();
```

IFC models often contain more than one context and bounding boxes are only expected to exist in some of them. So, if the processing applications uses contexts to filter what it is importing, it might be filtered out if you use the wrong one.

At the same time I can imagine that Revit might just ignore the bounding box completely because it doesn't have any direct equivalent in its data model and might be assumed to only be a generalised representation for an object with more detailed representation in other geometry context.

You would need to check Revit importer to find out if it supports import of bounding boxes at all. It would be great if you could publish your findings in this thread if you find anything interesting.

**Comment by nonLinearStifness** [comment]
Hello Carlos, I think that the problem is that you're using a bounding box.
You should use a sphere as representation and also tag the 3D annotation with the correct RepresentationType and RepresentationIdentifier. [See the IFC manual on 3D annotations for that](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Product_Shape/Product_Geometric_Representation/Annotation_Geometry/Annotation_3D_Geometry/content.html).

PS: Also working from ccg. :-p
