### ISSUE TITLE
Exception thrown when Validating an IFC File

### ISSUE THREAD

**Issue by Ravath** [xBimTeam/XbimEssentials#28]
I have found a bug.
When I try to validate some IFC files, a have an exception saying that : 
_firstOperande of Xbim.Ifc2x3.GeometricModelResource.IfcBooleanResult is null, at lines 118 and 126.

I believe it's not supposed to be, and better write down the problem in the validation output.

**Comment by martin1cerny** [comment]
Hi @Ravath ,
thank you for the bug report. You are right is should not crash. We are currently hard working on a next generation of xBIM which you can find in the `develop` branch. That is generally more robust and implements IFC4 as well as IFC2x3. The core schema implementation is code generated now which makes it very robust and reliable. But it also means we won't support schema validation because mapping EXPRESS functions to C# is very complex and challenging task.

**Comment by SteveLockley** [comment]
This is resolved in the Develop branch will will be published to Master very shortly
