### ISSUE TITLE
Deleting BuildingStorey leads to corrupt IFC file

### ISSUE THREAD

**Issue by shreyasanghvi** [xBimTeam/XbimEssentials#293]
When I try deleting the BuildingStorey, code executes without any error, but when opening in BIM Vision it, got error that IFCmodel is invalid

I tried below code 

var listBuildingStorey = model.Instances.OfType<IIfcBuildingStorey>().ToList();
model.Delete(listBuildingStorey[0]);

**Comment by bekraft** [comment]
You should have a look into the IFC specs (i.e. https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcbuildingstorey.htm). There are relations between the storey and the building elements. Relations are modeled explicitely. You have to remove them manually. Otherwise open relations remain within the model which becomes invalid therefore.

**Comment by shreyasanghvi** [comment]
Thanks for reply @bekraft ,

Yes, The first element of that list is BuildingStorey itself.

Can you tell me how the relations are modeled and how to remove it?
Is it IfcRelAggregates which defines relations between BuildingStorey and building elements?

**Comment by bekraft** [comment]
First you have to certain about the elements within the storey. Either you have to remove those too, or you have to find a new spatial container. Have a look into [IfcRelContainedInSpatialStructure](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/link/ifcrelcontainedinspatialstructure.htm). Since the referenced instances are spread in the model, you first need to collect all elements and their dependencies. The only way is graph traversal and deep knowledge of the IFC (since there are also different ways of modeling the same problem).

There's already a prepared workflow by the Xbim team using `InsertCopy(...)` method. You can pass in a filtering rule. It takes care of the relations by itself and transfers the modified IFC into a new model without affecting the current. See [Xbim InsertCopy Doc](http://docs.xbim.net/examples/insert-copy-function.html)
