### ISSUE TITLE
When I copy all entities of a big model, the model is destroyed.

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimEssentials#31]
I'm creating an algorithm exactly like CopyAllEntitiesTest.
And model is destroyed.
Look here:
http://imgur.com/gallery/MV6h5/new

**Comment by martin1cerny** [comment]
I'm sorry but 'destroyed' is not very descriptive. What is expected output? What does log4net say when you try to read the resulting file and create geometry?

**Comment by kozintsev** [comment]
Sorry but I do not know how to use log4net. I'll try to understand.

'destroyed' = Relations in the copied model is not bind objects

>>try to read the resulting file
Yes, of couse. In the screenshot there is a whole and destruction model

 >>and create geometry?
Not completely understood you.
In general, I have created the geometry using the xBim toolkit.
In this case, I did not use the functions to create geometry, just for copying entities.

**Comment by martin1cerny** [comment]
Log4Net is used as a logging tool in xBIM. It is heavily used in geometry engine to log any processing errors in the data. So if the problem was in a structure of geometry definitions it might show something. 

I had a look on your tests and you use obsolete `Ifc2x3.IO.XbimModel`
```cs
var target = Ifc2x3.IO.XbimModel.CreateTemporaryModel()
```
This is not maintained any more and might be removed in the future. It is recommanded to use `IfcStore` for any new projects.
```cs
var target = IfcStore.Create(IfcSchemaVersion.Ifc2X3, XbimStoreType.InMemoryModel);
```
Try this please.

**Comment by kozintsev** [comment]
No problem. Probably I was wrong.
