### ISSUE TITLE
Where is Xbim.Ifc2x3.Extensions ?

### ISSUE THREAD

**Issue by r3act** [xBimTeam/XbimEssentials#311]
Hi,

I am looking to use the SetMaterial() method on an IfcRoot object, but I cannot find that namespace.
From the documentation page : 
http://docs.xbim.net/XbimDocs/html/2b66f293-7e15-e5da-1397-56e70e3971d2.htm

Thanks

**Comment by Fagg0d** [comment]
Hi,

I've run into the same issue, can someone tell me the solution please?

Thanks

**Comment by martin1cerny** [comment]
We don't use these extensions any more because it was only very thin wrapper around the actual IFC schema. And for performance reasons it is much better to use the lower level directly. Inverse relations are particularly tricky in this and it is better if you design your code with the higher level of control.
