### ISSUE TITLE
How to support self defined schema?

### ISSUE THREAD

**Issue by FLYPoPo7** [xBimTeam/XbimEssentials#319]
We need to use custom schema. It's has some entity that doesn't exist in official ifc standard like 'IfcTunnel'. How to support entities like this? If it needs to change the code, what code do I need to change?

**Comment by martin1cerny** [comment]
We use internal code generation tool for this. Otherwise you can implement the extension if you follow the patterns in the code. We used the code generation for IfcRail pilot project which you can see [here in IfcRail branch](https://github.com/xBimTeam/XbimEssentials/tree/ifcRail) for example. But we tend to wait until the official release of the schema by buildingSMART.

**Comment by andyward** [comment]
We'll be picking this up officially in #353
