### ISSUE TITLE
Changing Direction of an Entity

### ISSUE THREAD

**Issue by tthmartin** [xBimTeam/XbimEssentials#337]
Hello, I'm trying to change the direction property of an entity.  Shortly, any direction it has, I want it to rotate so it would be "in front" of me.  I tried this code, but it's not working properly. Thank you in advance for your help!

using (var model = _model)
            {

                var fix = model.Instances.FirstOrDefault<IfcDirection>();

                //open transaction for changes
                using (var txn = model.BeginTransaction("Direction modification"))
                {
                    
                    fix.SetXYZ(0, 1, 0);
                    //commit changes
                    new Xbim3DModelContext(model).CreateContext();
                    txn.Commit();
                }

            }

**Comment by martin1cerny** [comment]
Direction is used extensively across various geometry definitions. This kind of change will likely destroy the whole model. You will only want to change direction of location objects of products I assume.

**Comment by tthmartin** [comment]
Yes you are right. Can you give me an example for how to do that? I searched and tried a lot of methods, but none of them work

**Comment by martin1cerny** [comment]
You need to look at [IfcProduct.ObjectPlacement](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcproduct.htm).

**Comment by tthmartin** [comment]
Thank you, but it is still not really clear for me. How can I change the coordinate property, so the model looks in another direction?

**Comment by bekraft** [comment]
The object placement holds transformation coordinate reference system. See [IfcLocalPlacement](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifclocalplacement.htm) (IFC4). Each placement consists of a axis placement (given a direction axis as X-axis and a reference axis as Z-axis) and a cartesian placement offset (aka translation). The final transformation is done by concatenating the transformation upwards to the root product (i.e. IfcSite).

So, if you like to rotate, change the reference axis placement by its reference axis in [IfcAxis2Placement3D](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcaxis2placement3d.htm).

For instance ```IFCDIRECTION((0.7071067811865458,0.70710678118654935,0.));``` will yield a 45 degree rotatio or ```IFCDIRECTION((0.,1.,0.));```  a 90 degree change.

Since the origin of rotation is relative to the placement coordinates, the final position will depend on the translation part (the local and global origin). When having huge offsets the result may be located somewhere at the opposite end of the world ...

**Comment by tthmartin** [comment]
Thank you, I understand now what I need, but I'm not sure how this methods work.

**Comment by bekraft** [comment]
What method? It's only data inside the IFC. 

A model being "in front of you" (as you said) depends on your camera transformation. Maybe you should have a look into scene graph transformation. Changes on the model have no effect on the camera (it's only data). So, maybe your approach changing the model isn't the most efficient way. It's more about camera settings and frontend behaviour ...

Concerning the model transformation: Using your code above, the crucial part is about how to find the proper IfcDirection (as @martin1cerny already said). So you have dig into the relations of the IfcLocalPlacement of your top IfcProduct (i.e. IfcSite or IfcBuilding, assuming you're about to rotate the whole model).

 - find the IfcProduct which you like to rotate
 - get the placement (and make sure you're not on a grid placement since it behaves in another way)
 - get the axis placement (using ```RelativePlacement``` attribute)
 - make sure that it is of type "IfcAxis2Placement3D"
 - get and change the ```RefDirection``` attribute - it is the X-axis direction of the rotation part

**Comment by martin1cerny** [comment]
I would add one more point:
- make sure to set `RefDirection` to new `IfcDirection` object in case it is referenced elsewhere. This is often the case when model has been "optimised".

**Comment by tthmartin** [comment]
Thank you so much for your help. You have been all very helpful!
