### ISSUE TITLE
IfcSIUnit keeps a static reference to an MemoryModel, leaking 16 - 35 MB

### ISSUE THREAD

**Issue by 0x53A** [xBimTeam/XbimEssentials#361]
I've memory profiled my application and noticed that even after closing all IFC files, XBim still keeps 35 MB RAM:

![image](https://user-images.githubusercontent.com/4236651/103672049-04ccc600-4f7c-11eb-808d-45da36397c79.png)

Here are the static roots:

https://github.com/xBimTeam/XbimEssentials/blob/8555eb3be90f9fb06711e6347c546a67ce9a36a7/Xbim.Ifc2x3/MeasureResource/IfcSIUnitPartial.cs#L12

https://github.com/xBimTeam/XbimEssentials/blob/8555eb3be90f9fb06711e6347c546a67ce9a36a7/Xbim.Ifc4/MeasureResource/IfcSIUnitPartial.cs#L20

And the issue is that the ``IfcDimensionalExponents`` keeps a reference to the ``IModel`` alive, keeping it from being garbage collected:

https://github.com/xBimTeam/XbimEssentials/blob/8555eb3be90f9fb06711e6347c546a67ce9a36a7/Xbim.Ifc4/MeasureResource/IfcDimensionalExponents.cs#L87

**Comment by martin1cerny** [comment]
Hi @0x53A , thanks for spotting this out. This code is in place for a very long time. I assume that your file contains huge amount of unit definitions? There are normally very few of these, that is why we didn't spot this I guess. It is only a speed optimization, so it should be fine to change it to be local instead of static. I'll have a look at it.

**Comment by 0x53A** [comment]
Thank you for the quick response!

> I assume that your file contains huge amount of unit definitions?

As far as I understand it, the issue isn't the unit definitions themselves, but rather that they keep the whole ``MemoryModel`` from being garbage collected.

![image](https://user-images.githubusercontent.com/4236651/103772761-503dad80-502a-11eb-9236-a6706be982e7.png)

Here the unit definitions themselves are only 1.6 kB, but they keep the MemoryModel and the IPersistEntity Dictionary alive.

**Comment by 0x53A** [comment]
I did a second test, where I just open an IFC file and immediatly close it:

```c#
    class Program
    {
        private static void Test()
        {
            using (IfcStore model = IfcStore.Open(@"file.ifc"))
            {
            }
        }

        public static void Main(string[] args)
        {
            Test();
            GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced, true, true);
            GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced, true, true);
            GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced, true, true);
        }
    }
```

Two memory snapshots, one before ``Test``, one after the ``GC.Collect``s.


![image](https://user-images.githubusercontent.com/4236651/103773746-d4446500-502b-11eb-8600-1306f0d4fadd.png)


![image](https://user-images.githubusercontent.com/4236651/103773300-22a53400-502b-11eb-8fd0-9f875303d8c7.png)

Now, I don't think these 11 MB "Leaks" (they are not really leaks, as they don't increase if you open multiple ifc files, they are "constant") will be noticed by many users, with typical RAM of > 8 GB.

I just noticed this while profiling my application and wanted to let you know.

**Comment by martin1cerny** [comment]
`ExpressMetadata` is not a leak. It is only created once for every schema (IFC2x3, IFC4, IFC4x3) when needed. And it is always reused for all metadata related operations. This is static intentionally and will not grow over time as you open/close as many models  as you want. 

Your initial case is different and would have an impact if you were opening and closing thousands of models (and accessing these dimensional exponents because these are lazy evaluated as you have noticed).
