### ISSUE TITLE
Question: how to use Memory Transactions to rollback/undo

### ISSUE THREAD

**Issue by Mopa2103** [xBimTeam/XbimEssentials#425]
Xbim.IO.Memory.Transaction class

Does anyone have an example of how to use the methods: Undo/Redo/DoReversibleAction?

Thanks for the wonderful job!

**Comment by martin1cerny** [comment]
Thanks, we are glad you like the Toolkit. These methods are used internally my IModel implementations and by IPersistEntity implementations. They are used to store actions so that the transaction as a block can be rolled back.  You can obviously use it to manage your own actions as well. What do you need to achieve?

**Comment by Mopa2103** [comment]
The question was how? 
Do you have an example of using them?
