### ISSUE TITLE
xBim.COBie.Client link gives a 404

### ISSUE THREAD

**Issue by Jero9999** [xBimTeam/XbimEssentials#51]
In the xBimEssentials readme there is a link in the Getting Started section that points to a xBim.COBie.Client application showing how to use the cobie integration stuff. It points to https://github.com/xBimTeam/XbimEssentials/blob/master
But that page does not exist.

**Comment by martin1cerny** [comment]
Hi @Jero9999 , I checked and the link in the Readme.md is actually not specified so GitHub points to the default path for the repository. It should point to [here](https://github.com/xBimTeam/XbimExchange/tree/master/Xbim.COBie.Client). At the same time you should probably have a look to [XbimExchange](https://github.com/xBimTeam/XbimExchange) project because as time goes we developed several ways how to work with COBie where Xbim.COBie.Client is the oldest one and it is no longer maintained.

**Comment by Jero9999** [comment]
Thanks Martin. And good tip about the XBimExchange.
