### ISSUE TITLE
[Failure] Could not find file 'C:\Users\DELL\Documents\xbim\XbimEssentials-master\SharedFileVersionInfo.cs'.

### ISSUE THREAD

**Issue by johnfoundations** [xBimTeam/XbimEssentials#52]
Top of tree does not build.  Things like utilities also do not build, because the Nuget package for essentials is not in any repository. Trying to test webui, but I cant find a wexbim file that is representative.

**Comment by martin1cerny** [comment]
I'm not sure what you mean by this. Our team has put great effort recently to publish stable packages both to [NuGet](https://www.nuget.org/packages/Xbim.Essentials.4/) and MyGet. We have changed the NuGet package ID because new version of xBIM is code braking and we don't want to force people to do substantial refactoring based on a simple upgrade of the package. If you were using `develop` branch recently you just need to reference new packages. 

If you use Visual Studio 2015+ add the following package sources:
  - https://www.myget.org/F/xbim-develop/api/v3/index.json
  - https://www.myget.org/F/xbim-master/api/v3/index.json

If you use Visual Studio 2013+ add the following package sources:
  - https://www.myget.org/F/xbim-develop/api/v2
  - https://www.myget.org/F/xbim-master/api/v2

**Comment by johnfoundations** [comment]
I tried that.  If you look at issues under xbimUtilties you will see:could not found xbim-essentials 4.0.0-v184 from shinyrabbit, which is not me.

This is what I get when I try the new versions.
I understand that you have been banging on IFC 4.
I tried to do the nuget today, for the first time.
Maybe I did something wrong, but I did include the 2 package sources for vs 2015 that you mention below.

**Comment by martin1cerny** [comment]
I just tried to build both the latest `master` and `develop` branches and both compile without any problem. Also if you don't need to change anything in a source code I'd encourage you to use either stable NuGet or less stable MyGet packages. These are all almost in sync now as I noted before.

**Comment by johnfoundations** [comment]
Hi. I will try the nuget. I am only interested in doing some work on the jscript part of the ui. I didn't see a Nuget package for the utilities, which is what I want, to convert a bit ifc into a wexbim.

**Comment by wizztjh** [comment]
I got this problem also , just add 
- right click tthe solution tree
- Add -> add item
- SharedAssemblyInfo.cs

**Comment by CBenghi** [comment]
SharedFileVersionInfo is a file generated automatically before the build of Xbim.Common.Csproj.
If you perform a build all this will be generated for you if missing.
If you still have problems try building Xbim.Common alone before building the other projects.
I'm closing the issue.
