### ISSUE TITLE
Reading STEP files

### ISSUE THREAD

**Issue by Basnederveen** [xBimTeam/XbimEssentials#545]
Hi all, i'm a bit confused.

I can see in the documentation in multiple places that it is possible to read STEP files using Xbim.

Over here the default IfcStore.Open method is used: https://docs.xbim.net/examples/step-to-xml-and-back-again.html

When I check the IfcStore source, I see in all IfcStore.Open methods that the only files supported are ifc, ifcxml, ifczip and xBIM.

Is it possible to read & parse step files using Xbim? 

I'm looking to read the files, edit/combine them, and then export them again.

**Comment by andyward** [comment]
OK, IFC and STEP (.stp) files **are** closely related but **not** the same. IFC significantly deviated from the original STEP standard. I suspect the confusion comes about because IFC files are commonly stored in IFC-SPF format: SPF stands for STEP Part 21 encoding ([ISO 10303-21](https://en.wikipedia.org/wiki/ISO_10303-21)). But fundamentally IFC and STP model different aspects of the physical world (buildings vs products) so each uses a different schema/payload, defined in EXPRESS. 

While xbim Essentials contains a generalised STEP 21 parser it expects the schema to be IFC (Ifc2x3, IFC4 etc). If doesn't support the STEP product schema. Even if you implemented the schema you'd need to than handle the specific geometries.

See also https://github.com/xBimTeam/XbimEssentials/issues/474#issuecomment-1371934605

It may be worth looking at something like https://github.com/ixmilia/step or similar

**Comment by Basnederveen** [comment]
Hi Andy,

Thank you for the reply. That is exactly where the confusion came from. 

Will look into that library, thanks for the link.
