### ISSUE TITLE
Exception on accessing ifcStore.DefaultOwningApplication if XbimEditorCredentials not provided on IfcStore.Create

### ISSUE THREAD

**Issue by MichaelBuehler** [xBimTeam/XbimEssentials#55]
In master branch (dll version 3.2):
The code in property IfcStore.DefaultOwningApplication assumes that _editorDetails is not null:
a.ApplicationName =  _editorDetails.ApplicationFullName;

However, _editorDetails remains null using constructor
 public static IfcStore Create(IfcSchemaVersion ifcVersion, XbimStoreType storageType)

Workaround: Provide editorDetails on Create()
 public static IfcStore Create(XbimEditorCredentials editorDetails, IfcSchemaVersion ifcVersion, XbimStoreType storageType)

**Comment by CBenghi** [comment]
Yes, something should be done here, but we still have to figure out a solution that applies to a number of other cases as well. 
I'll look into this in the coming days.
Thanks,
Claudio

**Comment by martin1cerny** [comment]
The reason is that when you use InsertCopy function and you want to keep entity labels (which is useful for extraction of partial models) you need to keep the model completely clear so that no entities are created internally. But it shouldn't lead to crash of course. Will fix it soon.

**Comment by martin1cerny** [comment]
I just fixed this but you should really provide editor details if you are going to change anything in the model because it keeps owner history right and makes sure that unique guids are assigned to all new IfcRoot objects as well as proper owner history object. Otherwise it is your responsibility to fill these in if you want to create a valid IFC model.
