### ISSUE TITLE
Not able to find the xBim.CodeGeneration tool

### ISSUE THREAD

**Issue by susanta-muni** [xBimTeam/XbimEssentials#67]
Hello,

I am not sure if this question is right in this forum or not. But an answer to the below question will be really helpful.

When I look into the components Xbim.Ifc4 and Xbim.Ifc2x3, I find a header "This code was generated by a tool Xbim.CodeGeneration". I am just wondering whether this tool is shared to public or is maintained internally?

Thanks in Advance

**Comment by martin1cerny** [comment]
Hi ssusanta kumar muni,

Xbim.CodeGeneration is our internal tool and is not public.

Martin

 "susanta kumar muni" <notifications@github.com>:

Hello,

I am not sure if this question is right in this forum or not. But an answer
to the below question will be really helpful.

When I look into the components Xbim.Ifc4 and Xbim.Ifc2x3, I find a header
"This code was generated by a tool Xbim.CodeGeneration". I am just
wondering whether this tool is shared to public or is maintained internally?

Thanks in Advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xBimTeam/XbimEssentials/issues/67>, or mute the thread

**Comment by susanta-muni** [comment]
OK. Thank you.
