### ISSUE TITLE
Net 3.5

### ISSUE THREAD

**Issue by daveime** [xBimTeam/XbimEssentials#72]
I'm trying to use the XbimEssentials and XbinGeometry libraries in a Unity project, which only supports up to net 3.5. However, some of the dependencies for these libraries don't seem to have versions below net 4.0.

Do I really have to find source for all the dependencies, try to compile them under net 3.5, and then compile these two libraries under 3.5, just to get this whole thing working with Unity, which would seem to be a common-sense target usage for these IFC libraries?

Is there no way to simply remove the log4net and ManagedEsent requirements in the build configuration of these two libraries? I'm using in-memory mode anyway, so have no need for the Windows database exposed by Esent anyway, and log4net is a glorified Console.WriteLine library.

Sorry for the tone, just a little frustrated by DLL hell and net versioning right now - this kind of nonsense should be a thing of the past.

**Comment by martin1cerny** [comment]
I am sorry but we don't have any specific configuration allowing to leave
these dependencies out. If you get the source, remove these two
dependencies and fix the code to compile (just delete ESENT related code
and leave log4net proxy class in Xbim.Common an empty shell) you should be
fine. You will obviously loose possibility to get the latest updates of
xBIM. I have already thought about splitting memory model and ESENT model
into two separate dlls to allow leaving it out but it won't be any soon.

Martin

2017-02-11 6:54 GMT+01:00 daveime <notifications@github.com>:

**Comment by CBenghi** [comment]
On top of what Martin suggests, you will have of course to downgrade the platform target for Geometry.
I seem to recall that there was some manual change needed around the c++ solution (a couple of years ago we had to revert a change from 4.5 to 4.0 because some of the users were not ready to upgrade framework).

If you run into problems have a look at the few commits I made just before and after 
Commit hash:  https://github.com/xBimTeam/XbimGeometry/commit/cf9b5f310b6726a83f7fd7cc242c6835a4d511c3
Date:		2 years ago (28/06/2015 17:25:39)

**Comment by daveime** [comment]
Okay, thanks for your prompt response guys. I've actually gone a different route to alleviate this, by using a client / server model. I created a server that does all the heavy lifting using the XBIM libraries and can be compiled under net 4.5, and then use sockets to communicate with a client built in Unity under net 3.5. Seems to be working out fine :-)
