### ISSUE TITLE
Unable to convert ifc to wexbim. #85

### ISSUE THREAD

**Issue by fouziyapatel** [xBimTeam/XbimEssentials#88]
@CBenghi 
I'm so sorry.You are taking it wrong way .I have added MyGet link but failed to get updated version of Xbim.Essentials and waiting to get it on NuGet. I think i must try again adding myget link in visual studio 2015.
Thanks.

**Comment by CBenghi** [comment]
Hello @fouziyapatel,
I am sorry I gave you the wrong impression. 
I've closed the issue #85 only because without the file we cannot help you or others to find the problem.

The nuget packages should work well with visual studio 2013 as well, if you get the right sources.

Otherwise, if you wish to try to convert to wexbim with the latest code you can [download the setup of XbimXplorer](http://docs.xbim.net/downloads/xbimxplorer.html), open the file and chose "export" from the file menu. This has only been re-enabled in the latest version a few moments ago, so you have to give the application enough time to update itself.

The squirrel version in the about box should be at least 4.0.12-V0039 for the export to work.

If opening the file works with explorer but wexbim does not then the application might give you more information on the error for us to help.

Best,
Claudio
