### ISSUE TITLE
Generating code from EXPRESS schema

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimEssentials#89]
Hello all,

I've read in Xbim 4 docs that the C# code is generated from IFC schema automatically. If I were to use some other IFC EXPRESS schema, can I use such tools to generate additional classes? Are those tools publicly available?

Best regards,
Uros

**Comment by martin1cerny** [comment]
I'm sorry but the tooling is not publicly available. Do you think of some specific schema?

**Comment by urosjovanovic** [comment]
Yeah, I'm interested in IFC Alignment schema which is still in active development but there is a draft available [here](https://bitbucket.org/tumcms/openinfraplatform-public/raw/93305268f479965f28bda69dceb282145f5cdafd/IfcAlignment1x1/schema/IFC4x1_RC3.exp). There are some new types added which I would like to read from the STEP file using Xbim.

Anyway, I will look for some other generators elsewhere, if you have any suggestions feel free to post.

Thanks for the prompt response,
Uros

**Comment by martin1cerny** [comment]
I'm not aware of any generators from EXPRESS to C# (or VB). That's why ended up developing our own which made it possible to automate design patterns developed over many years to fit IFC data structures. 

Saying so we might consider to make IfcAlignment part of Essentials in the future because I can see the potential for this.

**Comment by urosjovanovic** [comment]
We will probably manually add new entities from IFC Alignment into Xbim.Ifc4 module by using the same conventions that existing types follow. There are no major changes in this version from IFC4 Add1, as we can see [here](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0/html/link/ifc4-add1-to-ifc4x1-changelog.htm). If we end up with a working solution, maybe we can create a pull request to be placed into a separate branch for further development and research?

**Comment by martin1cerny** [comment]
Yes, you can do that. The question is which is the resulting schema, because EXPRESS file you pointed to above defines completely new schema `IfcAlignment1x1`. So it might be better to create new C# project as a copy of IFC4 schema and extend it as you have described. Once we support it in our code generation we could overwrite it and you could switch to it for future fixes and compatibility.

**Comment by meetbestzhe** [comment]
> 
> 
> I'm sorry but the tooling is not publicly available. Do you think of some specific schema?

Hi,martin1cerny ,I want to add IFCTunnel to sheme.Is this code generation tool  publicly available now？Thanks a lot.

**Comment by CBenghi** [comment]
Hi @meetbestzhe,

as far as I can tell there is no plan to release the code generation tool.
If you are interested in a small set of classes you can probably extend the code-base manually, if it's a bigger task we would have to consider this in the scope of a custom development project.

best,
Claudio
